### ISSUE TITLE
Steve's Big List of Issues

### ISSUE THREAD

**Issue by rushsteve1** [KO782KO/Jackscript#7]
# Steve's Big List of Issues

Hey you guys, It's Steven here to ruin your day. Jack said a while back that it would be helpful if I ran through some tests on this, so here it is. I opened a single issue because most of this is really minor, but should still be fixed.
This is all based on the latest .jar on the Master branch.
#### Project (Issues related to the source code and builds)
- **The project is almost 20mb uncompressed. Most of this is the EclipseLink files in dist/lib and lib/eclipselink. Deleting the eclipselink .jar from dist/lib did not cause an issue.**
- There a number of other possibly unneeded libraries.
- The dist/lib folder should be put IN the .jar/.exe
#### General
- ~~**If you close a subwindow using the 'X' it ends the whole application.**~~
- ~~**No error if invaild/taken ID number.**~~
- ~~**Files need to be generated on start**~~
- The jar is titled "jekscript". Also Jackscript is kinda a terrible name...
- Just causing the one window to change instead of spawning new ones would help with workflow.
- ~~**Thread does not properly close on 'X', but does when you click the Exit button.**~~
- The buttons on the menu are kinda wonky
- **Not loading Products.csv on lauch, therefore losing all the inventory.**
- When you have a menu open, and no text box selected, pressing Space is the same as clicking the back button and closes the open menu.
#### Manage Customers window
- ~~In the add new customer dialogue box, the text in the button doesn't fit.~~
- The "Add Existing Item" tab has nothing, and its name is confusing.
- How would the user know the ID number?
- ~~**Multiple customers can have the same ID. They are saved as two instances of the same person, regardless of name specified**~~
- No error if invalid phone number
- No error if invalid email
#### Manage Inventory
- The 'add existing items' tab has nothing other than a few default jLabels.
- Again, how would the user know the ID number?
- ~~When you add a new item it says "Export Successful"~~
- No error if invalid price
- No error if invalid quantity
#### Database Viewer
- ~~**Doesn't work. At all.**~~ This works nicely now.
- Background is wrong
- **A customers tab would be great to view customer info.**
#### Point of sale

I am mostly holding off because this is mostly unfinished. But...
- The theme is wrong.
- Isn't this just the "Create Order" screen?
- Button on the main menu is the wrong font.
#### Inventory Export
- ~~**Gives a .csv file that, when opened is a single cell of chinese characters and the unicode blank rectangle. So this is completely broken.**~~ Mostly Works now. An improvement
- If you try to overwrite an existing report, instead of overwritng report it creates a new report that ends with ".csv.csv"
#### Create Order
- ~~**Products don't show up in the dropdown.**~~ This is fixed
- "Amount of products" is cut off.
- ~~I can't even tell what that large box is for.~~
- ~~Final is not rounded to two decinals~~
- ~~Order type should default to "In Store"~~
- **The order should be processed BEFORE you press submit, and a confirmation window should appear.**
- **Being able to order multiple products from the "Create Order" screen**

Overall this DOES work.

This is now based on the newer .jar. Overall a few good improvements, but still a lot of issues. I put a few new ones i found on there too.

**Comment by AVCodee** [comment]
Hey there Steven! Thank you for the problems and issues you have found. I'm sure over the course of this week most of these problems will be ironed out. But for future reference, all JackScript's latest Alpha releases will be available on [this site](https://jackscriptblog.wordpress.com/)

**Comment by rushsteve1** [comment]
Ok so THAT version didn't even run. Gave me this:
./Jekscript.jar: line 1: $'PK\003\004': command not found
./Jekscript.jar: line 2: $'\bKluH': command not found
./Jekscript.jar: line 3:JluH���JqqMETA-INF/MANIFEST.MFManifest-Version:: No such file or directory
./Jekscript.jar: line 4: Ant-Version:: command not found
./Jekscript.jar: line 5: syntax error near unexpected token `('
'/Jekscript.jar: line 5:`Created-By: 1.8.0_66-b18 (Oracle Corporation)

**Comment by AVCodee** [comment]
That's odd. I just hopped onto a different computer to test it out and it worked just fine! Maybe check your java version?

**Comment by rushsteve1** [comment]
I updated the list.

**Comment by AVCodee** [comment]
Thanks for the feedback!

**Comment by rushsteve1** [comment]
Updated again at 12:20 on 3-24

**Comment by komalley97** [comment]
The issues with unfinished things are jacks fault. Please bug the crap out of him to get them done. Because hes lazy.

**Comment by komalley97** [comment]
Btw you should be basing these bugs on the latest .exe release.
